### ISSUE TITLE
Remaining definitions for model

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/opetopic-type-theory#7]
- [x] comma (slice)
- [ ] hom functor
- [ ] pullbacks
- [ ] fibred monads
- [ ] relative monoidal categories
- [ ] monoidal (bi)fibrations
- [ ] free monoids from monoidal fibrations
- [ ] nonstandard amalgamation signatures
- [ ] symmetric signatures
- [ ] symmetrization monad
- [ ] web monoid
- [ ] category of opetopes
- [ ] opetopic PERs

**Comment by freebroccolo** [comment]
Hmm, I guess since I'm using PERs, if this construction actually works it will yield a category of opetopic PERs instead of sets (or setoids) in the usual sense. Since the construction is also based quite directly on the idea of various kinds of signatures (this is closer the multicategory version of opetopes), maybe this would even have some significance for the abt/refinement stuff. I'm not focusing on binding at all for now but I don't see any fundamental reason why it couldn't be integrated into the rest of the machinery once everything is in place. /cc @jonsterling

**Comment by jonsterling** [comment]
It sounds plausible... I need to understand your development a bit better before I can remark intelligently on it, but it seems like that's what you'd have; if we could then what "operadic computation" means, we'd have something VERY interesting.

Am I right to think that you could say, an "opetopic PER" is an internal PER in the category `Psh(Opetopes)`, kind of like what I have got in the refinements machinery?

**Comment by freebroccolo** [comment]
So in the literature there are opetopes in the Baez-Dolan sense which have subsequently been reformulated in several different ways due to some subtle problems in the original definitions. This is based on a certain kind of iterated slice construction on operads.

However, there is another approach from Makkai et al. which instead starts with multicategories (sometimes called "multitopes"). Their version is also based on an iterated slice construction but it sounds cleaner and maybe better suited to a type theoretic setting. The very short explanation of it, from what I understand, is that you start with a signature and construct the free multicategory `M` over it. Then you have a functor into another kind of multicategory `M+` where the objects are arrows from `M` and then the arrows are these gadgets that describe how the original arrows compose and when they get "evaluated" (normalized) into maps from the original signature. Then you just start iterating this construction according to the dimension of opetopes you care about.

So in a way, opetopes are really about building precisely the right structures to track how all these maps compose in higher dimensions in terms of free tree-like structures induced from underlying signatures. To me, this is a much more logical/formal sounding approach than these other geometrically inspired methods which incidentally seem to have nice properties regarding groupoid constructions.

According to the literature, coherence issues in the opetopic setting are sort of trivially resolved simply by keeping track of the exact way in which things are composed: the universal arrows will necessarily be available "on-the-fly" if everything is constructed properly. (At least, this is my very crude, probably somewhat wrong understanding until I get further along).

The Kock et al version of opetopes via polynomials/containers is very elegant but I suspect it is not as well suited to a formalization like this which might eventually serve as a model for a concrete language via NBE. The multicategory approach seems better when working with inductive structures which would probably mean simpler formal proofs.

> Am I right to think that you could say, an "opetopic PER" is an internal PER in the category Psh(Opetopes), kind of like what I have got in the refinements machinery?

Yes, I think so. The only twist is that these would be PER-valued presheafs (in the same way they’d have to be setoid-valued otherwise).
